### ISSUE TITLE
Crawl of HTML spec fails on W3C server

### ISSUE THREAD

**Issue by tidoust** [tidoust/reffy#145]
Reffy's instance installed on W3C servers fails to parse the HTML LS spec. Crawl exits with a timeout error after 90s:

```
Error: Crawl took too long Error: Crawl took too long
  at Timeout._ [as _onTimeout] (/home/dom/github.com/reffy/src/cli/crawl-specs.js:351:29)
  at ontimeout (timers.js:498:11)
  at tryOnTimeout (timers.js:323:5)
  at Timer.listOnTimeout (timers.js:290:5)
```

While the spec is large, 90 seconds should be more than enough to parse it. Something else must be causing the issue (an out of memory error, perhaps?)

**Comment by tidoust** [comment]
Closing as issue was fixed some time ago by reducing the number of threads that run in parallel, using the `--max-old-space-size` parameter, and updating the version of Node.js that runs on the server:
https://github.com/tidoust/reffy/commit/7bb14276597f9e961f127031502c81299756cd57
